### ISSUE TITLE
Discuss retirement of zeebe-docker-compose

### ISSUE THREAD

**Issue by berndruecker** [camunda-community-hub/zeebe-docker-compose#52]
When this community extension was started, there was no docker-compose file available officially, and we also were still discussing recommended environments to run Zeebe.

In the meanwhile:

- there is one supported/maintained docker-compose file as part of the official get started (https://github.com/camunda-cloud/camunda-cloud-get-started/blob/master/docker-compose.yaml) 
- we agreed on docker-compose being an environment for development, but Kubernetes is the environment for production.

So I think we should probably retire this community project, because:

- we lack maintenance leading to versioning issues (see also https://github.com/camunda-community-hub/zeebe-docker-compose/issues/50)
- we are not up-to-date with product components (e.g. tasklist lacking completely)
- we offer configurations we do not support in docker-compose, but only in Kubernetes (especially around clusters)

I wanted to collect opinions first, probably especially calling out (but not limiting this to) @jwulf, @falko, @menski, @felix-mueller

**Comment by jwulf** [comment]
People use them to try it out. I know I use them to test things locally. I've been mostly running against the hosted instance for a while, so haven't updated them recently. 

To make it versioned, we could tag the releases, so people can check out tags.

**Comment by berndruecker** [comment]
But I think people should better use the official get-started compose file to test things locally (as stated above), where is the value of providing additional compose files, which probably even sketch a config we don't want to support (e.g. running a cluster in docker-compose or using simple monitor)?

**Comment by felix-mueller** [comment]
@berndruecker feel free to retire

**Comment by berndruecker** [comment]
I will now retire it - I added a DEPRECATION warning to the readme
